on:
  push:
    branches:
      master

jobs:
  build:
    name: Sphinx Pages
    runs-on: ubuntu-latest
    steps:
    - name: Start
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Sphinx Build
      uses: zhaoweiguo/sphinx-action@master
      with:
        docs-folder: "source/"
        build-command: "sphinx-build -b html . _build"

    - name: Clone documentation repo
      run: |
        git clone https://github.com/zhaoweiguo/www.zhaoweiguo.com.git  --branch master --single-branch zhaoweiguo
        rm -rf ./zhaoweiguo/kubernetes/*
        cp -r source/_build/* ./zhaoweiguo/kubernetes/
        cd ./zhaoweiguo
        git config --local user.email "zhaoweiguo@github.com"
        git config --local user.name "zhaoweiguo"
        git add .
        git commit -m "[github workflow kubernetes]Update changes"  -a || true


    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
        directory: zhaoweiguo
        repository: 'zhaoweiguo/www.zhaoweiguo.com'
        branch: master


    - name: Send dingding notify
      uses: zcong1993/actions-ding@master
      with:
        dingToken: ${{ secrets.DING_TOKEN }}
        secret: ${{ secrets.DING_SECRET }} # if secret set, action will call API with sign
        body: |
          {
            "msgtype": "link",
            "link": {
                "title": "GitHubAction",
                "text": "[GitHubAction]kubernetes is done!",
                "picUrl": "",
                "messageUrl": "https://www.zhaoweiguo.com/kubernetes"
            }
          }


